### ISSUE TITLE
License not fetched for python’s `pyparsing`

### ISSUE THREAD

**Issue by tushar-deepsource** [deepsourcelabs/depend#56]
When doing `depend --language=python --packages=pytest`, pyparsing's License is shown as "Other".

**Comment by NobleMathews** [comment]
Cant seem to replicate it anymore locally

**Comment by tushar-deepsource** [comment]
Please test it with both git clone and GitHub API methods!

**Comment by NobleMathews** [comment]
Pyparsing does give 2 different results based on the source because the [API response](https://pypi.org/pypi/pyparsing/3.0.9/json) gives us
`"license": ""`,  but should have used the classifier info `"License :: OSI Approved :: MIT License"`,
When it uses GitHub it straight up gets the repo license as MIT

Currently this behaviour is fixed by using the already existing handle_classifiers logic for setup.py and applying it to the API response - The name of equivalent Licenses need to be made more consistent though depending on the source
